packages:
  image: ubuntu:latest
  script:
  - apt-get update -qy
  - apt-get install -y curl python3-setuptools python3-wheel unzip
  - GLFW_VERSION=3.2.1
  # Build source distribution
  - python3 setup.py sdist
  # Build wheel for Windows x86
  - curl -L -o glfw.bin.zip https://github.com/glfw/glfw/releases/download/${GLFW_VERSION}/glfw-${GLFW_VERSION}.bin.WIN32.zip
  - unzip glfw.bin.zip -d glfw.bin
  - cp glfw.bin/*/lib-vc2010/glfw3.dll glfw/glfw3.dll
  - python3 setup.py bdist_wheel --python-tag py2.py3 --plat-name win32
  - rm -rf glfw.bin.zip glfw.bin glfw/glfw3.dll
  # Build wheel for Windows x86_64
  - curl -L -o glfw.bin.zip https://github.com/glfw/glfw/releases/download/${GLFW_VERSION}/glfw-${GLFW_VERSION}.bin.WIN64.zip
  - unzip glfw.bin.zip -d glfw.bin
  - cp glfw.bin/*/lib-vc2012/glfw3.dll glfw/glfw3.dll
  - python3 setup.py bdist_wheel --python-tag py2.py3 --plat-name win_amd64
  - rm -rf glfw.bin.zip glfw.bin glfw/glfw3.dll
  artifacts:
    paths:
    - dist/
